# Strategy details config file for BF trader  #
EVENTS:
  - Soccer
COMPETITIONS:
  - English Premier League
  - UEFA Champions League
MARKET_TYPEs:
  - MATCH_ODDS
MAX_EVENTS: 5
MIN_DAYS_TILL_START: 1
MAX_DAYS_TILL_START: 5
