# Strategy details config file for BF trader  #
#Filtering settings
EVENTS:
  - Soccer
COMPETITIONS:
  - English Premier League
  - UEFA Champions League
MARKET_TYPEs:
  - MATCH_ODDS
MAX_EVENTS: 5
MIN_DAYS_TILL_START: 1
MAX_DAYS_TILL_START: 5
NEWEST_FIRST: True

# Monitor timing configuration
UPDATE_FREQUENCY_TIERS:
  IN_PLAY: 5
  LESS_THAN_3H: 300
  LESS_THAN_6H: 900
  LESS_THAN_12H: 3600
  MORE_THAN_12H: 14400

INITIAL_UPDATE_FREQUENCY: 14400
STALE_TARGET_HOURS: 24
MONITOR_MAX_WAIT_SECONDS: 900
